### ISSUE TITLE
The Roadmap

### ISSUE THREAD

**Issue by peppelinux** [italia/spid-cie-oidc-nodejs#1]
We could also consider these points in your roadmap, if you find something to improve or define better or have ideas or contributions: you drive!

https://github.com/italia/spid-cie-oidc-aspnetcore/issues

please create your first milestone with all the features and issues to cover in your first release

**Comment by freddi301** [comment]
do you consider this issue solved?

**Comment by peppelinux** [comment]
Which releases we already have of this project and what's the version to be released until the end of this week?

**Comment by freddi301** [comment]
there is version [v0.0.0-alpha] published on npmjs
there will be version v0.0.1 tomorrow
