### ISSUE TITLE
No response from oidc/rp/providers call

### ISSUE THREAD

**Issue by alessia7** [italia/spid-cie-oidc-nodejs#40]
Hi,
I followed all instructions to run RP example project but the oidc/rp/providers call (when I click on "Entra con SPID" button) always responses with no data. The federation (0.0.0.0:8000) and cie provider (0.0.0.0:8002) work properly but I don't have any response in this case. 
I've registered the relying party and created new profile on the OIDC Federation Entity Administration (http://127.0.0.1:8000/admin/). 
I'm trying with the latest version of both projects spid-cie-oidc-nodejs and spid-cie-oidc-django.
Are there other tips I must follow?
![Schermata no providers - button](https://user-images.githubusercontent.com/49901951/164888955-aba40213-1145-43cf-b919-6e67a468cf2a.png)
<img width="1011" alt="Schermata no providers - postman" src="https://user-images.githubusercontent.com/49901951/164888962-2b77421f-6c51-41e5-b0a5-f58ba2a6804d.png">

**Comment by peppelinux** [comment]
In the log you can see the output of the trust chain, can you past it here?

anyway you have a CLI command to fetch, RP side, all the configured OPs in your settingslocal.py

````
examples/federation_authority/manage.py fetch_openid_providers --start -f
````

**Comment by freddi301** [comment]
Hi,
I updated the configuration readme [see here](https://github.com/italia/spid-cie-oidc-nodejs/blob/main/examples/express-react-relying-party/README.md).
Make sure you have correctly created `public.jwks.json` `private.jwks.json` `trust_marks.json` files in the `examples/express-react-relying-party` directory.

The reason there are no providers is that some error occurred during trust chain validation.

If the problem persist we can schedule a screen sharing session to debug the issue.

**Comment by freddi301** [comment]
You can also read the log files in the `logs` directory (it gets populated after starting the server on `127.0.0.1:3000`)

**Comment by alessia7** [comment]
I've already created these files in examples/express-react-relying-party directory.
As suggested, I found the error reading the log files! Here I read what is the problem: the sub configuration. I had configured RP sub 127.0.0.1:3000 and not 127.0.0.1:3000/oidc/rp. Changing this field I solved.

Thank you!
