### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by fautore** [italia/spid-cie-oidc-nodejs#91]
Hi, thanks for the work,
i was reading the documentation at `examples/express-react-relying-party/README.md` and i found out that the links that point to:
- `https://github.com/italia/spid-cie-oidc-django/examples/federation`
- `https://github.com/italia/spid-cie-oidc-django/examples/provider`

both lead to a 404 github page, i assume it's a broken link.

Thank you

**Comment by freddi301** [comment]
try with
- https://github.com/italia/spid-cie-oidc-django/tree/main/examples/federation_authority
- https://github.com/italia/spid-cie-oidc-django/tree/main/examples/provider

**Comment by peppelinux** [comment]
the links should be updated following this 
https://github.com/italia/spid-cie-oidc-django/tree/main/examples

could you please do a PR to get this result?

**Comment by fautore** [comment]
Thank you for the fast responses
